name = "Thesis"
defaultTargets = ["Thesis"]

[leanOptions]
pp.unicode.fun = true
linter.unusedVariables = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.13.0"

[[lean_lib]]
name = "Thesis"
